Fixing CloudTrail Validation Function
CloudTrail Validation Function show no data when launched into AWS, with following error: 

"
SyntaxError: Unexpected token u
at Object.parse (native)
at exports.handler (/var/task/index.js:24:31)
"
Can be fixed by changing ComplianceResourceTypes (line 269, rConfigRuleForCloudTrail) to AWS::CloudTrail::Trail (instead of EC2 Instance), and by removing the parse  "var ruleParameters = JSON.parse(event.ruleParameters);" (line 230) and ruleParameters Objects (line 212 & line 234).